export function pageLoad(content){

    const main = document.createElement('main');
    const titleDiv = document.createElement('div');
    const pageTitle = document.createElement('h1');

    const card = document.createElement('div')
    const description = document.createElement('p');
    const image = document.createElement('img');

    titleDiv.className = 'titleDiv';
    pageTitle.innerText = "Coffee Vibes";

    card.className = "card"
    description.innerText = "This is the most Awesome coffee out there. The art and the flaviour combine to give you the maximum expression of the coffee. Where the real and fiction is one, here our dreams comes true through the discipline generated by a good coffee.";
    pageTitle.className = "title";

    image.src = "https://steamuserimages-a.akamaihd.net/ugc/788632137952739176/8B1BD7371460AF8F0C08B7DC67B53A70476C06B9/?imw=512&&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false";
    image.className = "home__img"

    main.id = "main";
    main.className = "home__main"
    titleDiv.appendChild(pageTitle)

    card.appendChild(description);
    card.appendChild(image);

    main.appendChild(titleDiv);
    main.appendChild(card);
    content.appendChild(main);
}